name: Trigger auto deployment for flask

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/flask-AutoDeployTrigger-e9bece1b-73d1-4704-9b1c-8ae320bae203.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FLASK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FLASK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FLASK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: navaneethkrishna30.azurecr.io
          registryUsername: ${{ secrets.FLASK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FLASK_REGISTRY_PASSWORD }}
          containerAppName: flask
          resourceGroup: containers
          imageToBuild: navaneethkrishna30.azurecr.io/flask:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


